version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: project_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "4719:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - weblab820
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadminnaja
    environment:
      PMA_HOST: project_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "4748:80"  # เปลี่ยนจาก 4747 เป็น 4748
    depends_on:
      - db
    networks:
      - weblab820
    restart: always

networks:
  weblab820:
    driver: bridge

volumes:
  mysql_data:
    driver: local